name: build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  docker-build:
    name: Build Docker env
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v3
      - name: Get GitHub organization or user
        run: echo 'ORG='$(echo $(dirname ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Docker login
        env:
          DOCKER_USER = ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD = ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: soerenfindeisen/xodr-dev:${{ github.sha }}

  xodr-build:
    name: Compile in Docker
    needs: docker-build
    runs-on: ubuntu-latest
    container: 
      image: soerenfindeisen/xodr-dev:${{ github.sha }}
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: ./build.sh